"""
train.py - CatalogIQ ML Training Script
========================================
Uses all 1,000 rows from sample-input.csv.
Pseudo-labels are generated by the rule engine embedded here,
then 3 models are trained and saved:
  1. classifier.pkl      — LinearSVC for classpath / category
  2. brand_resolver.pkl  — LogisticRegression for brand
  3. confidence_scorer.pkl — XGBRegressor for confidence score
  4. tfidf.pkl           — shared TF-IDF vectorizer

  NOTE: The ML model here only handles classpath, brand, and confidence.
  The GPT agents (descriptionAgent, attributeAgent) handle generating
  descriptions and attributes.
"""

import os
import re
import sys
import io
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')
import json
import joblib
import numpy as np
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.svm import LinearSVC
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import cross_val_score
from sklearn.metrics import classification_report
from xgboost import XGBRegressor

# ── Paths ────────────────────────────────────────────────────────────────────
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CSV_PATH   = os.path.join(SCRIPT_DIR, "..", "src", "data", "sample-input.csv")
MODELS_DIR = os.path.join(SCRIPT_DIR, "models")
os.makedirs(MODELS_DIR, exist_ok=True)

# ── Rule engine (mirrors enrichmentPipeline.js) ───────────────────────────────
PLACEHOLDER_RE = re.compile(r"^--.*--$")

BRAND_KEYWORDS = [
    (re.compile(r"\bdiablo\b",              re.I), "DIABLO®"),
    (re.compile(r"\bmilw(aukee)?\b",        re.I), "MILWAUKEE®"),
    (re.compile(r"\b3m\b",                  re.I), "3M™"),
    (re.compile(r"\bmirka\b",               re.I), "MIRKA®"),
    (re.compile(r"\bhiolit\b",              re.I), "HIOLIT®"),
    (re.compile(r"\bmakita\b",              re.I), "MAKITA®"),
    (re.compile(r"\bdewalt\b|\bdcb\d",      re.I), "DEWALT®"),
    (re.compile(r"\bbosch\b",               re.I), "BOSCH®"),
    (re.compile(r"\bfrigidaire\b",          re.I), "FRIGIDAIRE®"),
    (re.compile(r"\bnorton\b",              re.I), "NORTON®"),
    (re.compile(r"\birwin\b",               re.I), "IRWIN®"),
    (re.compile(r"\bcubitron\b",            re.I), "3M™"),
    (re.compile(r"\btrex\b",                re.I), "TREX®"),
    (re.compile(r"\bazek\b",                re.I), "AZEK®"),
    (re.compile(r"\bkichler\b",             re.I), "KICHLER®"),
    (re.compile(r"\bfestool\b",             re.I), "FESTOOL®"),
    (re.compile(r"\bkreg\b",                re.I), "KREG®"),
]

CLASSIFICATION_RULES = [
    (re.compile(r"dishwasher",              re.I), "Appliances & Consumer Electronics > Kitchen Appliances > Built-In Dishwashers"),
    (re.compile(r"\bdryer\b",               re.I), "Appliances & Consumer Electronics > Laundry > Dryers"),
    (re.compile(r"\bfridge|refrigerator\b", re.I), "Appliances & Consumer Electronics > Kitchen Appliances > Refrigerators"),
    (re.compile(r"\brange\b",               re.I), "Appliances & Consumer Electronics > Kitchen Appliances > Ranges"),
    (re.compile(r"sanding belt",            re.I), "Abrasives > Coated Abrasives > Sanding Belts"),
    (re.compile(r"sanding disc|stikit|hiolit|abranet", re.I), "Abrasives > Coated Abrasives > Sanding Discs"),
    (re.compile(r"cut[- ]?off disc",        re.I), "Abrasives > Bonded Abrasives > Cut-Off Wheels"),
    (re.compile(r"faucet",                  re.I), "Kitchen & Bath > Fixtures > Sink Faucets"),
    (re.compile(r"(cplg|coupling)",         re.I), "Plumbing > Fittings > Couplings"),
    (re.compile(r"elbow",                   re.I), "Plumbing > Fittings > Elbows"),
    (re.compile(r"valve",                   re.I), "Plumbing > Valves"),
    (re.compile(r"drill bit",               re.I), "Power Tool Accessories > Drilling > Drill Bits"),
    (re.compile(r"\bblade\b",               re.I), "Power Tool Accessories > Cutting > Blades"),
    (re.compile(r"decking|deck board",      re.I), "Building Materials > Decking > Composite Decking Boards"),
    (re.compile(r"fascia",                  re.I), "Building Materials > Decking > Fascia Boards"),
    (re.compile(r"rail(ing)?\b",            re.I), "Building Materials > Decking > Railing"),
    (re.compile(r"baluster",                re.I), "Building Materials > Decking > Balusters"),
    (re.compile(r"chandelier|pendant|ceiling light|\blight\b", re.I), "Lighting > Fixtures > Interior Lighting"),
    (re.compile(r"\bglove",                 re.I), "Safety & PPE > Hand Protection > Gloves"),
]

def is_placeholder(v):
    return not v or bool(PLACEHOLDER_RE.match(str(v).strip()))

def parse_manufacturer(part_manuf):
    if not part_manuf:
        return "", ""
    m = re.match(r"^(.*?)\s*\(([^)]+)\)\s*$", str(part_manuf))
    if m:
        return m.group(1).strip(), m.group(2).strip()
    return str(part_manuf).strip(), ""

def resolve_brand(row, mfr_name, desc):
    for f in ["E1_Brand", "Unilog_Brand", "DIB_Brand"]:
        v = row.get(f, "")
        if not is_placeholder(v):
            return str(v).strip(), f, True
    for pattern, canonical in BRAND_KEYWORDS:
        if pattern.search(desc):
            return canonical, "description keyword match", True
    return mfr_name, "manufacturer fallback", False

def classify(desc):
    for pattern, path in CLASSIFICATION_RULES:
        if pattern.search(desc):
            return path, True
    return "Uncategorized > Needs Manual Classification", False

def count_attrs(desc, mpn):
    count = 0
    text = desc
    if mpn and text.startswith(mpn):
        text = text[len(mpn):].strip()
    if re.search(r"\bP(\d{2,4})\b", text):  count += 1
    if re.search(r"\d+\s?pc\b", text, re.I): count += 1
    if re.search(r"\d+\s?Disc/Box", text, re.I): count += 1
    if re.search(r"\d+.*x.*\d+", text, re.I): count += 1
    if re.search(r"\d+(?:\.\d+)?\s?v\b", text, re.I): count += 1
    if re.search(r"\d+(?:\.\d+)?\s?ft\b", text, re.I): count += 1
    return count

def score_confidence(has_mfr, brand_confident, class_confident, attr_count):
    score = 0
    if has_mfr:         score += 30
    if brand_confident: score += 25
    if class_confident: score += 25
    score += min(20, attr_count * 7)
    return score

# ── Load & pseudo-label ───────────────────────────────────────────────────────
print("=" * 60)
print("CatalogIQ ML Trainer — using all 1,000 rows")
print("=" * 60)

df = pd.read_csv(CSV_PATH)
print(f"[load] {len(df)} rows loaded from {CSV_PATH}")

records = []
for _, row in df.iterrows():
    mpn  = str(row.get("Mfg_Part_Num", "") or "").strip()
    desc = str(row.get("Part_Desc",    "") or "").strip()
    mfr_name, mfr_code = parse_manufacturer(row.get("Part_Manuf", ""))
    brand, brand_src, brand_conf = resolve_brand(row.to_dict(), mfr_name, desc)
    classpath, class_conf = classify(desc)
    attr_count = count_attrs(desc, mpn)
    confidence = score_confidence(bool(mfr_name), brand_conf, class_conf, attr_count)
    category   = classpath.split(" > ")[0]

    records.append({
        "mpn":        mpn,
        "desc":       desc,
        "brand":      brand,
        "classpath":  classpath,
        "category":   category,
        "confidence": confidence,
        "brand_conf": brand_conf,
        "class_conf": class_conf,
        "attr_count": attr_count,
        "has_mfr":    int(bool(mfr_name)),
        "brand_src":  brand_src,
    })

data = pd.DataFrame(records)
print(f"[label] Category distribution:\n{data['category'].value_counts().to_string()}\n")
print(f"[label] Brand distribution (top 10):\n{data['brand'].value_counts().head(10).to_string()}\n")

# ── Feature Engineering ────────────────────────────────────────────────────────
print("[features] Building TF-IDF features on Part_Desc...")

tfidf = TfidfVectorizer(
    ngram_range=(1, 2),
    max_features=8000,
    sublinear_tf=True,
    min_df=1,
    strip_accents="unicode",
    analyzer="word",
)

X_text = tfidf.fit_transform(data["desc"].fillna(""))
print(f"[features] TF-IDF shape: {X_text.shape}")

# Use TF-IDF as the single feature matrix for all 3 models
X = X_text

# ── 1. Product Classifier ─────────────────────────────────────────────────────
print("\n[train] Training LinearSVC — Product Classifier...")
le_class = LabelEncoder()
y_class = le_class.fit_transform(data["classpath"])

clf = LinearSVC(max_iter=2000, C=1.0, class_weight="balanced")
clf.fit(X, y_class)

cv_acc = cross_val_score(clf, X, y_class, cv=5, scoring="accuracy")
print(f"  [OK] 5-fold CV accuracy: {cv_acc.mean():.3f} +/- {cv_acc.std():.3f}")
print(f"  Classes: {len(le_class.classes_)}")

joblib.dump(clf,      os.path.join(MODELS_DIR, "classifier.pkl"))
joblib.dump(le_class, os.path.join(MODELS_DIR, "label_encoder_class.pkl"))
print("  Saved: classifier.pkl, label_encoder_class.pkl")

# ── 2. Brand Resolver ─────────────────────────────────────────────────────────
print("\n[train] Training LogisticRegression — Brand Resolver...")
le_brand = LabelEncoder()
y_brand = le_brand.fit_transform(data["brand"])

brand_clf = LogisticRegression(max_iter=1000, C=2.0, class_weight="balanced", solver="lbfgs")
brand_clf.fit(X, y_brand)

cv_brand = cross_val_score(brand_clf, X, y_brand, cv=3, scoring="accuracy")
print(f"  [OK] 5-fold CV accuracy: {cv_brand.mean():.3f} +/- {cv_brand.std():.3f}")
print(f"  Brands: {len(le_brand.classes_)}")

joblib.dump(brand_clf, os.path.join(MODELS_DIR, "brand_resolver.pkl"))
joblib.dump(le_brand,  os.path.join(MODELS_DIR, "label_encoder_brand.pkl"))
print("  Saved: brand_resolver.pkl, label_encoder_brand.pkl")

# ── 3. Confidence Scorer ──────────────────────────────────────────────────────
print("\n[train] Training XGBRegressor — Confidence Scorer...")
y_conf = data["confidence"].values.astype(float)

conf_reg = XGBRegressor(
    n_estimators=300,
    max_depth=5,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    verbosity=0,
)
# XGBoost needs dense; use extra features + sparse text as dense sample
conf_reg.fit(X_text, y_conf)

from sklearn.metrics import mean_squared_error
y_pred_conf = conf_reg.predict(X_text)
rmse = np.sqrt(mean_squared_error(y_conf, y_pred_conf))
print(f"  [OK] Train RMSE: {rmse:.2f} (train set; will use CV in production)")

joblib.dump(conf_reg, os.path.join(MODELS_DIR, "confidence_scorer.pkl"))
print("  Saved: confidence_scorer.pkl")

# ── Save TF-IDF ───────────────────────────────────────────────────────────────
joblib.dump(tfidf, os.path.join(MODELS_DIR, "tfidf.pkl"))
print("\n  Saved: tfidf.pkl")

# ── Save class metadata ───────────────────────────────────────────────────────
meta = {
    "num_classes": int(len(le_class.classes_)),
    "num_brands":  int(len(le_brand.classes_)),
    "classes":     list(le_class.classes_),
    "brands":      list(le_brand.classes_),
    "cv_class_acc":  round(float(cv_acc.mean()),  4),
    "cv_brand_acc":  round(float(cv_brand.mean()), 4),
    "conf_train_rmse": round(float(rmse), 2),
    "training_rows":   len(df),
}
with open(os.path.join(MODELS_DIR, "meta.json"), "w") as f:
    json.dump(meta, f, indent=2)

print("\n" + "=" * 60)
print("TRAINING COMPLETE!")
print(f"   Classifier  CV-accuracy : {cv_acc.mean():.1%}")
print(f"   Brand       CV-accuracy : {cv_brand.mean():.1%}")
print(f"   Confidence  train-RMSE  : {rmse:.2f}")
print(f"   Models saved to: {MODELS_DIR}")
print("=" * 60)
print("\nNext step: uvicorn predict:app --port 8000")
